import { StyleSheet } from "react-native"

export const colors = {
  bg: "#0a0a0a",
  bgCard: "#0d0d0d",
  bgSurface: "#111111",
  border: "rgba(255,255,255,0.06)",
  gold: "#d4a847",
  goldLight: "#f0d078",
  text: "#ffffff",
  textSecondary: "rgba(255,255,255,0.55)",
  textMuted: "rgba(255,255,255,0.3)",
  blue: "#60a5fa",
  purple: "#a855f7",
  green: "#22c55e",
  red: "#e74c3c",
  orange: "#f97316",
  beltBranca: "#e5e5e5",
  beltAzul: "#3b82f6",
  beltRoxa: "#9333ea",
  beltMarrom: "#92400e",
  beltPreta: "#1a1a1a",
  beltCoral: "#d4a847",
}

export const theme = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  card: {
    backgroundColor: colors.bgCard,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    padding: 16,
  },
  cardAccent: {
    backgroundColor: colors.bgCard,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    padding: 16,
    borderTopWidth: 4,
    borderTopColor: colors.gold,
  },
  input: {
    backgroundColor: "#141414",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 14,
    color: colors.text,
    fontSize: 15,
  },
  button: {
    backgroundColor: colors.gold,
    borderRadius: 12,
    padding: 16,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  buttonText: {
    color: "#000",
    fontSize: 15,
    fontWeight: "800",
  },
  label: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.textMuted,
    textTransform: "uppercase" as const,
    letterSpacing: 1,
    marginBottom: 6,
  },
  sectionHeader: {
    fontSize: 11,
    fontWeight: "900",
    color: colors.gold,
    textTransform: "uppercase" as const,
    letterSpacing: 2,
    marginBottom: 12,
  },
  statValue: {
    fontSize: 24,
    fontWeight: "900",
    color: colors.text,
  },
  statLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: colors.textMuted,
    textTransform: "uppercase" as const,
    letterSpacing: 1,
    marginTop: 2,
  },
})
